### PR TITLE
[Superseded by 1858] Add Istanbul block numbers to mainnet and goerli

### LINKED ISSUE #1839: Add Istanbul block number to mainnet
### What is wrong?

The mainnet network definition does not include Istanbul.

### How can it be fixed

- Wait for a block number to be picked for Mainnet.
- Add the block number to `eth/chains/mainnet/__init__.py`

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

Fixes #1839 

(also Goerli, which doesn't have an issue, I think)

### How was it fixed?

Added numbers based on: https://eips.ethereum.org/EIPS/eip-1679

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [x] Clean up commit history

[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: https://github.com/ethereum/py-evm/blob/master/newsfragments/README.md)

[//]: # (See: https://py-evm.readthedocs.io/en/latest/contributing.html#pull-requests)
- [x] Add entry to the [release notes](https://github.com/ethereum/py-evm/blob/master/newsfragments/README.md)

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by carver** [comment]
Trying to get a py-evm release out today

**Comment by carver** [comment]
cc @cburgdorf in case you have thoughts on the benchmark updates

**Comment by voith** [comment]
FYI, @veox has made similar updates in https://github.com/ethereum/py-evm/pull/1858

**Comment by carver** [comment]
Ah, thanks @voith I'll try to use that one instead.

**Comment by carver** [comment]
Merged in #1871

**Pull request closed without merging**
