### PR TITLE
memoize multiple utility functions

### PR DESCRIPTION
**Pull request by pipermerriam**
STUB: been meaning to test whether this has a noticeable speed improvement.

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by pipermerriam** [comment]
@carver @dylanjw thoughts on this?

Looking at the test run times I don't think I can objectively say this produced a significant speed improvement, but it *shouldn't* have slowed anything down.  Memory footprint of memoizing these function calls should be reasonably low.

My *gut* says to hold off until we can implement some sort of global caching framework so that it's up to users what sort of memory footprint they want to allow for this sort of thing.

**Comment by carver** [comment]
Hm, without a clear speed improvement, I'm a very slight 👎 . Out of curiosity, can we get a measurable speedup if you massively increase cache size?

**Comment by pipermerriam** [comment]
> Out of curiosity, can we get a measurable speedup if you massively increase cache size?

I doubt it.  There are roughly two or three optimizations at play here depending on how you look at it.

1. JSON-fixture tests use many of the same addresses for contracts, transactions, etc.
2. There are a few values that just natively get used a lot like 32 null bytes or empty byte string.
3. There are a few storage values that are going to be common, like lower integers.

The optimizations happen wtih

- `evm.db.hash_trie.HashTrie` which uses `keccak(key)` as the key when storing in the trie.
- `evm.vm.stack` which moves values back and forth between integer and bytes representations (`int_to_big_endian/big_endian_to_int`).
- `evm.db.state` which uses `pad32` for it's storage keys.

I'm going to try bumping the cache sizes.  Maybe `64` was a bit too small and these common values were constantly being evicted.  Will check run-times in the morning and see what things look like.

**Comment by pipermerriam** [comment]
Not seeing any noticeable speed increases. 👎

**Pull request closed without merging**
