### PR TITLE
[2/3] Linted file with isort in eth and tests directory

### PR DESCRIPTION
**Pull request by prathmeshranaut**
### What was wrong?

Imports are not sorted.

Closes Issue #2094 

### How was it fixed?

Added `isort`, a tool to sort imports, in the linting process.

Adding lint setup + linting files would be a large PR to review. I've decided to split it up into 3 parts. 
[First PR](https://github.com/ethereum/py-evm/pull/2098)

```mermaid
flowchart LR
    pr1[Added isort to setup, makefile and tox] --> pr2[Linted file with isort in eth and tests directory - This PR]
    pr2 --> pr3[Add isort check to tox]
```

This is second PR of a two part linting rollout. In this PR, I ran `make lint-roll`. 
In order to validate and review the PR quickly, you can checksum `eth` and `tests` directory.

Let me know if I missed anything in the contribution process.

### Todo:
- [x] Clean up commit history

- [x] Add or update documentation related to these changes

- [x] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

#### Cute Animal Picture

images

### CODE REVIEW

**Comment by prathmeshranaut** [comment]
@pacrob Rebased with master and is ready for review.

**Comment by pacrob** [comment]
Hey @prathmeshranaut, thanks for moving on this. We're working on a refactor related to #2089, and it'll much easier get that merged then re-lint-roll than the other way around. I'll comment back here when we're ready to apply. Thanks!

**Comment by pacrob** [comment]
Thanks for your help on this @prathmeshranaut ! I decided to just cherry-pick the "adding isort to tox" commit into this PR and made a couple small tweaks, and it should be ready to go!

Closes #2094
Closes #2103

**Review by fselmo — APPROVED** [review]
lgtm 👍🏼. Slight preference for putting the `isort` config into its own `.isort.cfg` file to keep `tox.ini` focused on tox-specific configs but we can figure that out at the template level later.

**Pull request merged**
