### PR TITLE
fix-unclean-shutdown: remove db.ipc, if present

### LINKED ISSUE #1040: fix-unclean-shutdown doesn't seem to help here
### What is wrong?

Need to investigate further, just a quick dump to not forget.

```
$ trinity
    INFO  07-18 11:52:50        main  
      ______     _       _ __       
     /_  __/____(_)___  (_) /___  __
      / / / ___/ / __ \/ / __/ / / /
     / / / /  / / / / / / /_/ /_/ / 
    /_/ /_/  /_/_/ /_/_/\__/\__, /  
                           /____/   
    INFO  07-18 11:52:50        main  Trinity/0.2.0a26/linux/cpython3.6.5
    INFO  07-18 11:52:50        main  Trinity DEBUG log file is created at /home/cburgdorf/.local/share/trinity/mainnet/logs/trinity.log
    INFO  07-18 11:52:50        main  Started DB server process (pid=27313)
    INFO  07-18 11:52:50        main  Started networking process (pid=27314)
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/profiling.py", line 31, in inner
    return fn(*args, **kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/logging.py", line 118, in inner
    return fn(*args, **inner_kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/main.py", line 249, in run_database_process
    serve_chaindb(chain_config, base_db)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/chains/__init__.py", line 258, in serve_chaindb
    server = manager.get_server()  # type: ignore
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 482, in get_server
    self._authkey, self._serializer)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 139, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 576, in __init__
    self._socket.bind(address)
OSError: [Errno 98] Address already in use
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/profiling.py", line 31, in inner
    return fn(*args, **kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/logging.py", line 118, in inner
    return fn(*args, **inner_kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/main.py", line 288, in launch_node
    node = NodeClass(plugin_manager, chain_config)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/nodes/full.py", line 26, in __init__
    super().__init__(plugin_manager, chain_config)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/nodes/base.py", line 63, in __init__
    self._db_manager.connect()  # type: ignore
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 489, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
(venv) cburgdorf at craftbot in ~/Documents/hacking/ef/py-evm on christoph/tests/trinity-integration*
$ trinity fix-unclean-shutdown
    INFO  07-18 11:53:10        main  Cleaning up unclean shutdown...
    INFO  07-18 11:53:10        main  Found 0 processes from a previous run. Nothing to do.
(venv) cburgdorf at craftbot in ~/Documents/hacking/ef/py-evm on christoph/tests/trinity-integration*
$ trinity
    INFO  07-18 11:53:16        main  
      ______     _       _ __       
     /_  __/____(_)___  (_) /___  __
      / / / ___/ / __ \/ / __/ / / /
     / / / /  / / / / / / /_/ /_/ / 
    /_/ /_/  /_/_/ /_/_/\__/\__, /  
                           /____/   
    INFO  07-18 11:53:16        main  Trinity/0.2.0a26/linux/cpython3.6.5
    INFO  07-18 11:53:16        main  Trinity DEBUG log file is created at /home/cburgdorf/.local/share/trinity/mainnet/logs/trinity.log
    INFO  07-18 11:53:16        main  Started DB server process (pid=27441)
    INFO  07-18 11:53:16        main  Started networking process (pid=27442)
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/profiling.py", line 31, in inner
    return fn(*args, **kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/logging.py", line 118, in inner
    return fn(*args, **inner_kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/main.py", line 288, in launch_node
    node = NodeClass(plugin_manager, chain_config)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/nodes/full.py", line 26, in __init__
    super().__init__(plugin_manager, chain_config)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/nodes/base.py", line 63, in __init__
    self._db_manager.connect()  # type: ignore
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 489, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/profiling.py", line 31, in inner
    return fn(*args, **kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/logging.py", line 118, in inner
    return fn(*args, **inner_kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/main.py", line 249, in run_database_process
    serve_chaindb(chain_config, base_db)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/chains/__init__.py", line 258, in serve_chaindb
    server = manager.get_server()  # type: ignore
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 482, in get_server
    self._authkey, self._serializer)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 139, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 576, in __init__
    self._socket.bind(address)
OSError: [Errno 98] Address already in use
```

### How can it be fixed

:see_no_evil: :hear_no_evil:

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

Fixes #1040 

### How was it fixed?

- at end of fix-unclean-shutdown, remove `db.ipc` file, and log out what happened

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by pipermerriam** [comment]
No opposition.  Want to go into the settings and uncheck the options you don't want us using.

cc @gsalgado and @cburgdorf

**Comment by cburgdorf** [comment]
@pipermerriam well, in general keeping rebase and squash available from the UI is a good thing imho because often it is convenient to clean up wip commits (especially from external contributors) without having to do that locally.

**Comment by carver** [comment]
I don't think I've ever gotten a github UI rebase to work the way I wanted it to, but I'm not opposed to keeping squash around for external contributors who aren't savvy to cleaning up their commit history.

**Comment by pipermerriam** [comment]
Mostly I just click the green button.  Ignoring PRs with really bad commit histories, I'm largely indifferent about how they get merged.  I can start selecting merge from now on though.

**Pull request merged**
