### PR TITLE
Implement bitwise shift opcodes for Constantinople

### PR DESCRIPTION
**Pull request by cburgdorf**
### What was wrong?

As stated in https://github.com/ethereum/py-evm/issues/1104, the upcoming Constantinople fork adds three new opcodes for bitwise shifting operations. Namely `SHL`, `SHR` and `SAR`. This PR adds support for the `SHL` and `SHR` opcodes.

This does **not** include support for the `SAR` opcode yet which is expected to land in another PR. https://github.com/ethereum/py-evm/pull/1134

### How was it fixed?

1. Created a new `test_opcodes` file and wrote a couple of tests for existing opcodes. This isn't finished but from the perspective of this PR it shouldn't matter and we have an open issue to not forget about testing other existing opcodes #1111 

2. Implemented `SHR` and `SHL` logic in `eth.vm.logic.arithmetic`
3. Added all test cases from the [EIP](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-145.md#test-cases)
3. Added opcodes that expose the functionality to the constantinople opcodes

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by cburgdorf** [comment]
@pipermerriam failing CI seems like something related to the new network abstraction and unrelated to this PR as far as I can tell. https://circleci.com/gh/ethereum/py-evm/50905?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by pipermerriam** [comment]
@cburgdorf see https://github.com/cburgdorf/py-evm/pull/1 for how to do this without the library.

**Comment by pipermerriam** [comment]
Regarding test failure: https://github.com/ethereum/pytest-asyncio-network-simulator/pull/6 incoming

**Comment by pipermerriam** [comment]
@cburgdorf you should be able to rebase this now and pass CI

**Comment by carver** [comment]
Can we start running selected Constantinople state tests now?

**Comment by pipermerriam** [comment]
> Can we start running selected Constantinople state tests now?

@carver yes, but my recommendation would be to do that in a separate PR.  We'll need to update the commit that our fixtures are current set at (probably to whatever is in geth master?) and then fix anything that is broken.

**Comment by cburgdorf** [comment]
@pipermerriam @carver Alright, I decided to branch of #1134 for the `SAR` opcode because I really need to ramp up my unicon bits & bytes skills for that one (Or maybe I just need to pick your brain more @carver :sweat_smile:)

So, this one is ready for review if anyone is up for it.

**Pull request merged**
