### PR TITLE
chore: update eth dependencies

### PR DESCRIPTION
**Pull request by unparalleled-js**
### Todo:

[//]: # (Stay ahead of things, add list items here!)
- [ ] Clean up commit history

[//]: # (See: https://py-evm.readthedocs.io/en/latest/contributing.html#pull-requests)
- [ ] Add entry to the [release notes](https://github.com/ethereum/py-evm/blob/master/newsfragments/README.md)

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by carver** [comment]
Every time you tighten a dependency, it is a breaking change which can cause significant downstream effects. If it's really as easy "we don't use any APIs that changed between these major versions" then maybe we can increase the upper version and leave the lower version in place.

**Review by carver — APPROVED** [review]
👍🏻 (with a squash merge if @unparalleled-js doesn't beat us to it with a squash rebase 😄 )

**Comment by unparalleled-js** [comment]
> I screwed up the release numbering, so this is actually done in py-evm `0.5.0-alpha.2`. The corresponding eth-tester version that should work with these dep updates is: `0.6.0-beta.5`, and web3py `v6.0.0-beta.2`. Thanks for the PR though @unparalleled-js! I think it may make sense to release the `0.5.0-alpha.2` changes as `0.6.0-alpha.1` though so I'll put that on my list.

I for some reason am unable to get these updates!  I am installing via `web3[tester]`:

```
"web3[tester]>=5.29.1,<6.0"
```

and every time, it gives me old versions of `eth-utils` `eth-abi` etc. When I try to update them, the conflicts always brings me back to `py-evm`

**Comment by kclowes** [comment]
This needs to be: 
`"web3[tester]>=6.0.0,<7.0"`

**Pull request closed without merging**
