### PR TITLE
Pypy support

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

pypy was not being tested in CI. There were a few little incompatibilities left.

### How was it fixed?

- add pypy3 tests
- remove pysha3 from p2p
- use eth-hash's `new()` to get an object that can be updated sequentially
- upgrade eth-hash so that we can call `update()` after `digest()`

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by pipermerriam** [comment]
Can you add the conditional `toolz/cytoolz` install pattern too?

**Comment by pipermerriam** [comment]
For now, what do you think about only testing `p2p/trinity` with pypy?

**Comment by carver** [comment]
Pro testing more tox envs:
- find out faster if a pypy3 breakage slips in
Pro testing fewer tox envs:
- PRs can be merged faster, and generally give faster feedback

I think -- *at least for now* -- that the tradeoff should go the direction of quicker iteration at the cost of maybe missing a pypy breakage. Maybe that should change as trinity gets more stable.

---

Update: Leveldb is causing headaches. Looks like we would have to build a custom docker container, because the default one doesn't support a recent enough version of `libleveldb-dev` (1.20 according to [this issue](https://github.com/wbolster/plyvel/issues/62)). This may be a good idea, as would be building a fully compiled version of trinity in docker. But I've already spent more time on this than I intended. So I'll pause and return later.

**Comment by ninjaahhh** [comment]
since pypy3 only supports python3.5, how about some language features currently used in this repo like variable annotations?

**Comment by carver** [comment]
This PR is super old. We will probably drop py3.5 support soon, sooner than pypy will add py3.6 support. So I'll close this until it makes sense to resurrect.

**Pull request closed without merging**
