### PR TITLE
Migrate util usage to eth_utils

### PR DESCRIPTION
**Pull request by cburgdorf**
### What was wrong?

Came across this while working on something else. Seems we had some helpers in `eth.utils.numeric` that we also have in `eth_utils`. Guess those were in place from a time where `eth_utils did not exist or at least did not have these methods.

### How was it fixed?

Migrated to `eth_utils`.

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by pipermerriam** [comment]
These are the only lines where that function is used where the difference in behavior would manifest:

- https://github.com/ethereum/py-evm/blob/master/eth/utils/transactions.py#L51
- https://github.com/ethereum/py-evm/blob/master/eth/vm/forks/spurious_dragon/transactions.py#L22
- (maybe) https://github.com/ethereum/py-evm/blob/master/eth/vm/stack.py#L75

**Comment by pipermerriam** [comment]
The two functions behave the same in all cases **except** for `0`.

- `eth_utils.int_to_big_endian(0) -> b'\x00'`
- `eth.utils.numeric.int_to_big_endian(0) -> b''`

**Comment by pipermerriam** [comment]
> IMO `None` should be handled as a separate case rather than expecting `int_to_big_endian` to convert it to `b''`.

Yeah, I would expect/want `int_to_big_endian(None)` to throw an exception.

**Comment by cburgdorf** [comment]
>Interesting, it looks like the default value of None would crash here

https://github.com/ethereum/py-evm/blob/19aed7a379ca643ac051ffd94ea2d8dc8c01579f/eth/utils/transactions.py#L46-L51

But the `if chain_id` prevents it from hitting that branch anyway. Btw, if you hit `y` on your keyboard, github generates a link to the commit (rather than the branch) and does then inline the code snippet instead of just rendering the link.

However, it's not that. The reason this failed is because our `modexp` precompile had a bug that previously wasn't exposed because `int_to_big_endian` had a bug (kinda).

I changed the `modexp` precompile to be inline with what geth does.

**Comment by carver** [comment]
> Btw, if you hit y on your keyboard, github generates a link to the commit (rather than the branch)

neat! :tada: 

> But the if chain_id prevents it from hitting that branch anyway.

oops :man_facepalming: 

> I changed the `modexp` precompile to be inline with what geth does.

:+1:

**Pull request merged**
