### PR TITLE
Upgrade py-ecc past a buggy release, to 1.4.6

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

py-ecc was pinned to an old version to resolve a bug.

### How was it fixed?

Upgrade py-ecc past the buggy release.

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by carver** [comment]
Looks like some flake8 errors made it into master. I'll go through all the other PRs/Issues before trying to fix it here.

**Comment by veox** [comment]
Experiencing same `lint` CI run failure as here ATM in PR #1579.

(Subscribing myself so I get to see how to fix it.)

**Comment by cburgdorf** [comment]
>which now exposes it's type hints

[PEP561 at work](https://www.python.org/dev/peps/pep-0561/), beautiful

**Comment by hwwhww** [comment]
@carver @pipermerriam 
Fix `py_ecc`: https://github.com/ethereum/py_ecc/pull/40
`py-evm` side: https://github.com/hwwhww/py-evm/commit/a326a0e90c9dddad184b0dd05e018bf40df9a719

* A few `FQP_point_to_FQ2_point` transformation, not a perfect solution here...
On the other hand, I'm not sure if we should make it looser by just making all `FQ2` and `FQ12` type hinting to `FQP`. Might need to think about it more after or during https://github.com/ethereum/py_ecc/issues/31.

* Also will need another `py_ecc` version bump + update `py-evm` requires.

**Comment by hwwhww** [comment]
@pipermerriam thank you! 👍 

@carver hwwhww@a326a0e passed the CI: https://circleci.com/gh/hwwhww/py-evm/tree/pr1576

**Pull request merged**
