### PR TITLE
More type annotations for Trinity

### PR DESCRIPTION
**Pull request by cburgdorf**
This adds more type hints to trinity

### CODE REVIEW

**Comment by gsalgado** [comment]
@cburgdorf I'm not sure if you're adding all those type annotations manually, but there are some [tools that can help with that](https://github.com/ethereum/py-evm/issues/132#issue-271406378)

**Comment by cburgdorf** [comment]
I'm do adding them manually but I'm gonna look at those tools. But while adding them manually may sound like super boring monkey work I kinda enjoy getting my feet wet with the code base that way. You naturally have to browse through the entire code base and start thinking about the code :)

**Comment by cburgdorf** [comment]
I cleaned this up to something that I think is good to merge if CI goes green. I actually have some more changes locally but those are more controversial / experimental with stuff like the [`TypedDict`](http://mypy.readthedocs.io/en/latest/kinds_of_types.html#typeddict) from `mypy_extensions`. I need to play with those changes more before I propose something.

I also left out the `trinity/rpc` stuff because I think it's currently much in flux and needs a bigger refactoring (As mentioned in https://github.com/ethereum/py-evm/pull/437).

**Comment by cburgdorf** [comment]
One job timed out. Otherwise, looks green.

**Comment by pipermerriam** [comment]
looks like this needs a rebase.

**Comment by cburgdorf** [comment]
Yep, rebased.

**Pull request merged**
