### PR TITLE
DOC: building-chains: syncing documentation with source code

### PR DESCRIPTION
**Pull request by lacabra**
### What was wrong?

the documentation available at http://py-evm.readthedocs.io/en/latest/building_chains.html is out of sync with the source code on how to setup a LightChain

### How was it fixed?

Documentation was updated providing instructions that work with the actual codebase

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by carver** [comment]
Maybe this would be a good time to try out a doctest, so we catch it when the docs fall out of sync.

**Comment by pipermerriam** [comment]
@lacabra you can check out how @carver implemented doctests in the `eth-hash` codebase (I think that's where it was).

**Comment by carver** [comment]
It was in the local signing code of web3: https://raw.githubusercontent.com/ethereum/web3.py/master/docs/web3.eth.account.rst

**Comment by pipermerriam** [comment]
Going ahead and merging as-is.  Some doctests would still be great @lacabra if you want to take that on.  Otherwise, thanks for getting this updated.

**Pull request merged**
