### PR TITLE
Cleaning up evm.utils.numeric

### PR DESCRIPTION
**Pull request by hiteshramani**
### What was wrong?
The `evm.utils.numeric` required cleanup. Issue -> #568 

### How was it fixed?
I modified and removed certain methods from the module which were not being used. `safe_ord` which was being used was safely modified.

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by cburgdorf** [comment]
Thanks for the PR @hiteshramani ! Can you rebase on top of latest master to get the CI to pass?

**Comment by hiteshramani** [comment]
@cburgdorf I suggest the flake8 linter should be configured on the developer's side, and the README should include how to configure the linter as a pre-commit hook to avoid unnecessary failures due to lint errors. What do you think?

**Comment by cburgdorf** [comment]
>I suggest the flake8 linter should be configured on the developer's side

You should definitely run `flake8` locally to get early feedback but we still need to run it as part of CI as a *last line of defence* so to speak 

>and the README should include how to configure the linter as a pre-commit

I'm *personally* not a friend of pre-commit hooks for this because my workflow does lots of work in progress commit which I cleanup later. I don't want git to yell at me about anything at this stage. Not even about totally broken code.

But you are correct that our README falls short on any guidance regarding code style. We do have a [style guide](https://github.com/pipermerriam/ethereum-dev-tactical-manual/blob/master/style-guide.md) that also mentions `flake8` and we also have a general [contribution guide](http://py-evm.readthedocs.io/en/latest/contributing.html#code-style) that highlights a couple of other things but none of this is mentioned in the README and I agree we should at least have some pointers there.

**Comment by pipermerriam** [comment]
I'd vote for just a dedicated section about how to run the linting tests, maybe as a *checklist* for things that developers should do prior to pushing commits. (though I'm not sure what else would go in this section).

**Pull request merged**
