### PR TITLE
Make PeerPool available earlier

### PR DESCRIPTION
**Pull request by cburgdorf**
### What was wrong?

Currently the `PeerPool` on the server appears asynchronously some time later after initialization. See #877. This turns out as being problematic as we often want to pass the `PeerPool` somewhere else without passing the entire server.

### How was it fixed?

The reason the `PeerPool` doesn't immediately appear on the server today is because the server asynchronously awaits on the upnpdevice before it can build the `DiscoveryProtocol` that the ` `PeerPool` depends on.

Now what this PR does is that it allows the `PeerPool` to accept a `Future[DiscoveryProtocol]` instead of a `DiscoveryProtocol`.

I'm not super sold on that because it essentially just pushes the problem one level down (now the `PeerPool` will *sometimes* have the `DiscoveryProtocol` appearing asynchronously sometime after initialization.

The other alternative would be to make all methods that depend on the `DiscoveryProtocol` async but I'm not sure how far that would creep through all depending APIs.

As I'm working on the minimal Tx pool, I figured that I may need the `PeerPool` to be available early so I'm laying this out here for further discussion.

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by gsalgado** [comment]
What if instead we simplified `PeerPool` by moving the responsibility of doing peer discovery to some other component (e.g. `p2p.Server`)?  That way `PeerPool` would only need to provide APIs to add new peers to the pool and notify its subscribers about them. I think it doesn't make sense for `PeerPool` to handle discovery anyway, and that would allow us to fix this issue in a cleaner way

**Comment by cburgdorf** [comment]
@gsalgado I agree on that and in fact I was considering it for a moment but I then wasn't sure how feasible that would be. Now that *you* bring it up I'm inclined to give that more thought.

However, since we have #898 waiting on this and also #904 making changes to the `PeerPool` would be ok to take it as is and open up a ticket to follow up with that refactoring later?

**Comment by gsalgado** [comment]
How urgent is #898? I'll have a look at moving discovery to `p2p.Server` today

**Comment by cburgdorf** [comment]
@gsalgado would be nice if it makes it into the next release (I think we are aiming for one this week) but if it doesn't that's not the end of the world either. Anyway, if you're looking into this today, we'll wait. :+1:

**Comment by cburgdorf** [comment]
Replaced by #934. Closing.

**Pull request closed without merging**
