### PR TITLE
Replace cytoolz with eth_utils.toolz

### LINKED ISSUE #1711: Update all `toolz` imports to come from `eth_utils.toolz`
Loosely depends on https://github.com/ethereum/py-evm/pull/1710 to ensure `eth-utils` is new enough.

### What is wrong?

We have `toolz/cytoolz` compat via `eth_utils.toolz` but this library still directly uses `cytoolz`

### How can it be fixed

Update all `toolz` imports to come from `eth_utils.toolz`

```
from cytoolz import assoc
# should become
from eth_utils.toolz import assoc
```

### PR DESCRIPTION
**Pull request by stringray55**
### What was wrong?
fixes #1711 

### How was it fixed?
used grep and replace 

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by stringray55** [comment]
Can someone please help me with the mypy errors. Have no clue about it.

**Comment by pipermerriam** [comment]
@stringray55 those are unrelated.  This PR is :+1: and we'll handle the rebase once the upstream fix for `eth-bloom` has been released.

**Comment by pipermerriam** [comment]
@stringray55 if you can rebase against master these tests will pass and we can get this merged.

**Comment by cburgdorf** [comment]
I took it up and did the rebase. Will merge once it goes green.

**Pull request merged**
