### PR TITLE
Suppress ImportWarning messages

### PR DESCRIPTION
**Pull request by rayrapetyan**
This commit fixes ImportWarning-s issue (#1402, #1370). As mentioned in referred issue, this is a Cython bug fixed in master and not yet available. We can't fix it in py-evm modules.
A suggested [workaround](https://bugs.launchpad.net/lxml/+bug/1732505/comments/4) was used.

### CODE REVIEW

**Comment by rayrapetyan** [comment]
I did everything I could to bypass CircelCI checks (even re-created pull request from the scratch), but it keeps an old copy of chains/base.py file and fails on all imports there... "Erroneous" line numbers correspond to empty lines in base.py.

**Comment by carver** [comment]
Is it working for you when you run tox locally?

**Comment by rayrapetyan** [comment]
Yeah, kind of... Nevermind, I’ve found a workaround. Please review. Thanks!

**Comment by pipermerriam** [comment]
FYI, I think this is the core issue: https://github.com/cython/cython/issues/1720

**Comment by pipermerriam** [comment]
@rayrapetyan I'm inclined to wrap this so that it's easier for us to clean these up later.

```python
import contextlib
import warnings

def catch_and_ignore_import_warning():
    with warnings.catch_warnings():
        warnings.simplefilter('ignore', category=ImportWarning)
        yield
```

This should then be usable like this:

```python
with catch_and_ignore_import_warning():
    from eth_utils import (
        to_set,
        ValidationError,
    )
```

This will have to go somewhere that we can get it without triggering any of these warnings.  I'd be fine putting it somewhere like `eth._warnings` (`eth/_warnings.py`).

Thoughts?

**Comment by rayrapetyan** [comment]
Well it looks reasonable for a permanent fix, but for a temp fix and just 4 places introducing a separate file on a root level... looks an overkill, but up to you, I can do that.

**Comment by rayrapetyan** [comment]
After syncing master there are 7 places to fix, so looks reasonable to save one line in each place, committed with _warnings.py file.

**Comment by pipermerriam** [comment]
> Well it looks reasonable for a permanent fix, but for a temp fix and just 4 places introducing a separate file on a root level... looks an overkill, but up to you, I can do that.

- DRY: if we found that there was an extra piece of logic needed for this to work right a week from now we might not remember to update all of the call sites.
- In a similar vein it will be easier to find all of the locations and clean them up when the core issue is fixed.

:+1: Will give this some final review on Monday.

**Pull request merged**
