### PR TITLE
Removed the duplicate functions

### LINKED ISSUE #1407: Remove duplicate utility functions from `eth.tools.fixtures.normalization`
### What is wrong?

from: https://github.com/ethereum/py-evm/pull/1396#pullrequestreview-165796731

There are duplicates of some of the functions in:

- `eth.tools._utils.normalization`
- `eth.tools.fixtures.normalization`

Specifically the `normalize_int` but there may be others.

### How can it be fixed

Audit these two modules for duplicate functions and remove the duplicates.  In the case of `normalize_int`, the `_utils` one should be kept.  Use your best judgement on any others that are found.

### PR DESCRIPTION
**Pull request by isaacelee**
I removed the duplicate functions from /fixtures/normalization.py mainly except the
functions under the header "Fixture Normalizers" as I felt those belonged and as
such removed them from /_utils/normalization.py instead.
Meant to fix #1407

### CODE REVIEW

**Comment by pipermerriam** [comment]
@isaacelee lots of failed tests.  Looks like you need to spend some time updating the imports for some of these to import from the right location.

**Comment by isaacelee** [comment]
Not sure if I've made a complete mess of things trying to update my fork with the master branch, let me know if I need to create a new pull request and I can try and refork and do it right the first time. Hopefully this sorts everything out and sorry about the delay, midterm exams.

**Comment by pipermerriam** [comment]
This PR will need to be fixed as it's history isn't something we can merge.  I'd recommend going and reading up on how to do a `git rebase`.

**Comment by cburgdorf** [comment]
Apart from the PR not getting the rebase it needs, this was fixed in https://github.com/ethereum/py-evm/pull/1486

**Pull request closed without merging**
