### PR TITLE
Update `trie` to v2.0.0

### PR DESCRIPTION
**Pull request by Uxio0**
- Fix dependency issues with typing-extensions

### CODE REVIEW

**Comment by sunwrobert** [comment]
@fselmo @kclowes can we please get this merged in?

**Comment by kx9x** [comment]
waiting for this to get in 🙏

**Comment by kclowes** [comment]
The release numbering got screwed up, so this is actually released in v0.5.0-alpha.2. Let me know if you're still having dependency issues after installing v0.5.0-a.2.

**Comment by Uxio0** [comment]
With `v0.5.0-a.2` it's even worst:

```bash
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
web3 5.29.0 requires eth-typing<3.0.0,>=2.0.0, but you have eth-typing 3.0.0 which is incompatible.
web3 5.29.0 requires eth-utils<2.0.0,>=1.9.5, but you have eth-utils 2.0.0 which is incompatible.
eth-rlp 0.2.1 requires eth-utils<2,>=1.0.1, but you have eth-utils 2.0.0 which is incompatible.
eth-rlp 0.2.1 requires rlp<3,>=0.6.0, but you have rlp 3.0.0 which is incompatible.
eth-keyfile 0.5.1 requires eth-utils<2.0.0,>=1.0.0-beta.1, but you have eth-utils 2.0.0 which is incompatible.
eth-account 0.5.7 requires eth-keys<0.4.0,>=0.3.4, but you have eth-keys 0.4.0 which is incompatible.
eth-account 0.5.7 requires eth-utils<2,>=1.3.0, but you have eth-utils 2.0.0 which is incompatible.
eth-account 0.5.7 requires rlp<3,>=1.0.0, but you have rlp 3.0.0 which is incompatible.
eth-abi 2.1.1 requires eth-typing<3.0.0,>=2.0.0, but you have eth-typing 3.0.0 which is incompatible.
eth-abi 2.1.1 requires eth-utils<2.0.0,>=1.2.0, but you have eth-utils 2.0.0 which is incompatible.
```

**Comment by kclowes** [comment]
I just did a fresh pip install of py-evm v0.5.0a2 in a new virtualenv and pip was able to resolve everything

**Comment by Uxio0** [comment]
With a clean and new virtualenv:
```
    eip712-structs 1.1.0 depends on eth-utils>=1.4.0
    py-evm 0.5.0a2 depends on eth-utils<3.0.0 and >=2.0.0
    web3 5.29.0 depends on eth-utils<2.0.0 and >=1.9.5
```

**Comment by sunwrobert** [comment]
all I'm trying to do is install `gnosis-py` with `eth-brownie` also installed but this one thing is completely blocking me 😅 from doing so. @Uxio0 you have any workarounds?

**Comment by kx9x** [comment]
Would also love workarounds for getting the latest brownie version working with gnosis-py. I am still stuck on brownie like 1.17, which doesn't support new ganache.

Stuck in dependency hell

**Comment by kclowes** [comment]
@Uxio0 if you need to use `trie` v2.0.0, and web3.py, you'll have to use web3's master branch currently. I'll try and get a release out today so you can pin to web3 v6.0.0-b.2, but there may be some breaking changes to address. Let me know if that doesn't work for some reason and we can figure something else out. I'll going to reopen this, because discussion is still ongoing, but if using web3 v6.0.0-beta.2 works feel free to close. 

Is there a feature in trie v2.0.0 that you need to use? I'm curious how this started.

**Comment by Uxio0** [comment]
> Is there a feature in trie v2.0.0 that you need to use? I'm curious how this started.

Hi @kclowes , not really anything from `trie v2` that we want to use, we are tied because of the `typing-extensions` dependency (I already opened a PR there removing it https://github.com/ethereum/py-trie/pull/127). That's what's preventing people from updating `eth-brownie`

**Comment by sunwrobert** [comment]
+1 on just re-emphasing the need for anything that can be done to expedite/solve this. The team at OpenSea will be eternally grateful.

**Comment by kclowes** [comment]
> we are tied because of the typing-extensions dependency (I already opened a PR there removing it https://github.com/ethereum/py-trie/pull/127)

Ahh, got it. Thanks for the ping on that PR, it got buried. I will work on this stuff today and hopefully get something released next week. 

In the meantime, I did release web3.py v6.0.0b2 yesterday. Dependencies should resolve with `web3.py v6.0b2` and `py-evm v0.5.0a2` in our stack but it sounds like we may need that [py-trie PR](https://github.com/ethereum/py-trie/pull/127) before brownie can resolve.

**Comment by Uxio0** [comment]
Sounds good, thank you very much for all your work @kclowes

**Comment by carver** [comment]
It looks like the next step on this is to update rlp in the setup.py to `>=3,<4`.

**Comment by carver** [comment]
Although maybe this is all taken care of in #2062 ?

**Comment by fselmo** [comment]
Closing as this all seems to have been resolved 🤔 ... feel free to re-open or ask to re-open if not.

**Pull request closed without merging**
