### PR TITLE
Christoph/review/1420

### PR DESCRIPTION
**Pull request by cburgdorf**
Temp PR to diagnose errors

### CODE REVIEW

**Comment by Bhargavasomu** [comment]
Some installation problem with the `RocksDB`.

**Comment by cburgdorf** [comment]
@Bhargavasomu yep, trying to figure out why...because I haven't had any problems after rebasing https://github.com/ethereum/py-evm/pull/1424 on top of latest master

**Comment by Bhargavasomu** [comment]
@cburgdorf , #1181 failed for the same reasons, by looking at the details given by `circleci`

**Comment by Bhargavasomu** [comment]
@cburgdorf #1431 seems to make the necessary header files accessible. Could you please take a look at it? I have made a link to the header files, which I don't think was previously present. But it is taking a lot of time to run the test cases. Is this because I have cleared the cache somewhere?

**Comment by cburgdorf** [comment]
@Bhargavasomu nice find. I rebased this on top of #1431 just to double check :)

**Comment by pipermerriam** [comment]
I'm fine with us rolling back #1416 for now until we get #1426 in place or something similar which makes this more reliable.

**Comment by pipermerriam** [comment]
you can bust the cache by incrementing the `v1/v2` numbers in the cache strings in the `./circleci/config` file.  But given that this has happened more than once (already happened to me once while trying to get the PR green), I suspect it'll happen again.

**Pull request closed without merging**
