### PR TITLE
EIP-1884: Reprice trie-size dependent opcodes

### LINKED ISSUE #1826: EIP-1884: Repricing for trie-size-dependent opcodes
For Istanbul: https://eips.ethereum.org/EIPS/eip-1884

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

Fixes #1826 

### How was it fixed?

Changed pricing, and added selfbalance opcode, added tests.

Bonus simplification in the insufficient stack exception.

### To-Do

- [x] Add tests defined in the EIP
- [x] Rebase on #1828 

[//]: # (Stay ahead of things, add list items here!)
- [x] Clean up commit history

[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: https://github.com/ethereum/py-evm/blob/master/newsfragments/README.md)

[//]: # (See: https://py-evm.readthedocs.io/en/latest/contributing.html#pull-requests)
- [x] Add entry to the [release notes](https://github.com/ethereum/py-evm/blob/master/newsfragments/README.md)

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by carver** [comment]
I'll send the SSTORE one christoph's way, since he worked on that last time, so I am switching this review request from christoph to @pipermerriam .

**Comment by carver** [comment]
Are you up for pairing with me on it today? I'm starting to spin a little bit on what approach to take to build the test. I haven't used the filler before, and maybe I'm doing it wrong.

**Comment by pipermerriam** [comment]
@carver I can do it tomorrow (Friday).  I'm not confident the fillers are the right tool but happy to work with you to find out if it is.

**Comment by carver** [comment]
Piper from other channel:

> let's leave your tests as is and forget the fillers for now

**Pull request merged**
